# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy (as np)

#### Set the seed to 0

#### Create an array of 10 zeros 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 (in order)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

#### Create a 5x5 matrix with values ranging from 0 to 8

array([[4, 7, 5, 0, 3],
       [3, 3, 7, 1, 3],
       [5, 2, 4, 7, 6],
       [0, 0, 4, 2, 1],
       [6, 7, 7, 6, 0]])

#### Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

1.1253141037750505

#### Use NumPy to generate a 5x5 matrix of 25 random numbers sampled from a standard normal distribution

array([[ 0.81526991,  0.22909795, -1.02617878,  0.47752547,  1.29269823],
       [-0.73145824, -1.60540226,  0.98947618,  0.11081461, -0.38093141],
       [ 0.11495917,  0.34531264, -1.73495876,  1.65835111,  2.29977152],
       [-0.47113526,  1.26271548, -1.17051545,  1.0657892 , -0.69993739],
       [ 0.14407911,  0.3985421 ,  0.02686925,  1.05583713, -0.07318342]])

#### Create the following matrix (hint: use `linspace` with `reshape`):

Expected result:
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

#### Create an array of 20 linearly spaced points between 0 and 1:

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [1]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [2]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
20
```

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[ 2],
       [ 7],
       [12]])

```

In [3]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([21, 22, 23, 24, 25])

```

In [4]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW

```python 
[Output]:
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

### Conditional Indexing (AKA fancy indexing)

In [10]:
import numpy as np
np.random.seed(0)

In [11]:
mat = np.random.randint(-5, 50, size=[5,5])
mat

array([[39, 42, 48, -5, -2],
       [-2, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])

#### Select all elements that are greater than 5.

Expected result:
```python
array([39, 42, 48, 34, 14, 16, 45, 31, 18, 19, 19,  7, 33, 34, 18, 41, 19,
       12, 32])
```

#### Select all rows where the first element is less than or equal to 20.

Expected result:
```python
array([[-2, 34,  4, 14, 16],
       [19,  7, -4, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Replace all negative elements with 0.

Expected result:
```python
array([[39, 42, 48,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Calculate the sum of all elements that are less than or equal to 5.

Expected result: `5`

### Calculate the mean of all elements in the last column.

Expected result: `20.2`

#### Count the number of elements that are not equal to 0.

Expected result: `21`

#### Replace all elements equal to the maximum value of the matrix with 0.

Expected result:
```python
array([[39, 42,  0,  0,  0],
       [ 0, 34,  4, 14, 16],
       [45, 31, 18,  1, 19],
       [19,  7,  0, 33, 34],
       [18, 41, 19, 12, 32]])
```

### Math on rows and columns

#### Add 5 to a all mat elements

In [56]:
mat = mat + 5

#### Get the sum of all the values in mat

603

#### Get the standard deviation of the values in mat

15.007518115931095

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

#### Get the sum of all the rows in mat

# Great Job!